title: AWARE Test Site V1.0
description: Near real-time visualizations of carbon, methane, and water fluxes at US-EML
theme: jekyll-theme-minimal
markdown: kramdown
plugins:
  - jekyll-seo-tag
include:
  - assets/css/style.css